// export const cachedBounties = [];

// export const highscores = [];

export const numberOfBounties = [3, 3, 3, 3, 3]; // Number of bounties per tier, 3 is temporary

//holds current highscores created by parsing sheets data
export const highscores = [
  { Player_Name: "Happy", Score: 69, TotalBounty: 420.69 },
  { Player_Name: "Thorn", Score: 24, TotalBounty: 4.5 },
  { Player_Name: "Reagan", Score: 21, TotalBounty: 4.2 },
  { Player_Name: "Vinny", Score: 18, TotalBounty: 3.9 },
  { Player_Name: "Pubes", Score: 14, TotalBounty: 3.5 },
  { Player_Name: "Yalongbone", Score: 11, TotalBounty: 2.5 },
  { Player_Name: "Mason", Score: 10, TotalBounty: 1.75 },
  { Player_Name: "Dubz", Score: 5, TotalBounty: 0.5 },
  { Player_Name: "Kirk", Score: 2, TotalBounty: 0.005 },
  { Player_Name: "Wash", Score: 1, TotalBounty: 0.002 },
];
//Holds all current bounty objects ()UPDATE TO EMPTY ON SERVER
export const cachedBounties = [
  {
    Id: "2",
    Difficulty: "easy",
    Title: "Bandos Champion",
    Item: [
      "Bandos hilt",
      "Bandos tassets",
      "Bandos boots",
      "Bandos chestplate",
    ],
    Source: "General Graardor",
    Description: "",
    Type: "",
    Bounty: "0.5",
    Wiki_URL: "https://oldschool.runescape.wiki/w/General_Graardor",
    Status: "Active",
    Other: "",
    RSN: "",
    Discord: "",
    S3_URL: "",
    Quantity: "",
    Sheet_Index: 2,
    Wiki_Image: "https://oldschool.runescape.wiki/images/General_Graardor.png",
    Tier_completed: false,
    Completed: false,
  },
  {
    Id: "2",
    Difficulty: "medium",
    Title: "Graardors booty",
    Item: ["Bandos tassets"],
    Source: "General Graardor",
    Description: "Go rip them panties offa Graardor",
    Type: "LOOT",
    Bounty: "0.5",
    Wiki_URL: "https://oldschool.runescape.wiki/w/Cadantine",
    Status: "Active",
    Other: "",
    RSN: "",
    Discord: "",
    S3_URL: "",
    Quantity: "",
    Sheet_Index: 2,
    Wiki_Image: "https://oldschool.runescape.wiki/images/Cadantine.png",
    Tier_completed: false,
    Completed: false,
  },
  {
    Id: "2",
    Difficulty: "hard",
    Title: "",
    Item: ["hard item"],
    Source: "Something else",
    Description: "Test Desc",
    Type: "CLUE",
    Bounty: "1",
    Wiki_URL: "https://oldschool.runescape.wiki/w/Cadantine",
    Status: "Active",
    Other: "",
    RSN: "",
    Discord: "",
    S3_URL: "",
    Quantity: "",
    Sheet_Index: 2,
    Wiki_Image: "https://oldschool.runescape.wiki/images/Cadantine.png",
    Tier_completed: false,
    Completed: false,
  },
  {
    Id: "2",
    Difficulty: "elite",
    Title: "",
    Item: ["elite item"],
    Source: "Something else",
    Description: "Test Desc",
    Type: "CLUE",
    Bounty: "1",
    Wiki_URL: "https://oldschool.runescape.wiki/w/Great_Olm",
    Status: "Active",
    Other: "",
    RSN: "",
    Discord: "",
    S3_URL: "",
    Quantity: "",
    Sheet_Index: 2,
    Wiki_Image: "https://oldschool.runescape.wiki/images/Great_Olm.png",
    Tier_completed: false,
    Completed: false,
  },
  {
    Id: "1",
    Difficulty: "master",
    Title: "Go fuck up Graardor",
    Item: ["Bandos hilt"],
    Source: "General Graardor",
    Description: "Test Desc",
    Type: "LOOT",
    Bounty: "0.5",
    Wiki_URL: "https://oldschool.runescape.wiki/w/Verzik_Vitur",
    Status: "Active",
    Other: "",
    RSN: "",
    Discord: "",
    S3_URL: "",
    Quantity: "",
    Sheet_Index: 1,
    Wiki_Image: "https://oldschool.runescape.wiki/images/Verzik_Vitur.png",
    Tier_completed: false,
    Completed: false,
  },
];
